### ISSUE TITLE
Unable to download, invalid app secret

### ISSUE THREAD

**Issue by MrBonesHOK** [vitiko98/qobuz-dl#124]
Just started getting the InvalidAppSecret error, even after resetting the config. Any ideas?

**Comment by LimaHotel807** [comment]
I'm having the same issue. Was working fine a few days ago.

**Comment by MrBonesHOK** [comment]
Think I saw an old problem about this on here from a  yr or so ago regarding the same, think Qobuz updated something

**Comment by Jodel-D18** [comment]
Same for me.  Was working fine yesterday, but I get the same InvalidAppSecretError.

**Comment by letotor** [comment]
Same for me... connected OK but when I enqueue title ,album I obtained this log: ( centos stream 8 python>3 )

```
Traceback (most recent call last):
  File "/usr/local/bin/qobuz-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/qobuz_dl/cli.py", line 174, in main
    qobuz.initialize_client(email, password, app_id, secrets)
  File "/usr/local/lib/python3.6/site-packages/qobuz_dl/core.py", line 73, in initialize_client
    self.client = qopy.Client(email, pwd, app_id, secrets)
  File "/usr/local/lib/python3.6/site-packages/qobuz_dl/qopy.py", line 39, in __init__
    self.cfg_setup()
  File "/usr/local/lib/python3.6/site-packages/qobuz_dl/qopy.py", line 204, in cfg_setup
    raise InvalidAppSecretError("Invalid app secret.\n" + RESET)
qobuz_dl.exceptions.InvalidAppSecretError: Invalid app secret.
Reset your credentials with 'Traceback (most recent call last):
  File "/usr/local/bin/qobuz-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/qobuz_dl/cli.py", line 174, in main
    qobuz.initialize_client(email, password, app_id, secrets)
  File "/usr/local/lib/python3.6/site-packages/qobuz_dl/core.py", line 73, in initialize_client
    self.client = qopy.Client(email, pwd, app_id, secrets)
  File "/usr/local/lib/python3.6/site-packages/qobuz_dl/qopy.py", line 39, in __init__
    self.cfg_setup()
  File "/usr/local/lib/python3.6/site-packages/qobuz_dl/qopy.py", line 204, in cfg_setup
    raise InvalidAppSecretError("Invalid app secret.\n" + RESET)
qobuz_dl.exceptions.InvalidAppSecretError: Invalid app secret.
Reset your credentials with 'qobuz-dl -r'
'
```


Same problem after with Command : qobuz-dl -r

**Comment by Khalathir** [comment]
Same here, getting the same InvalidAppSecretError.

**Comment by pinus2** [comment]
same also here

**Comment by coreyoilar** [comment]
Same problem here too. Was working great, went to bed and let it run overnight, got up yesterday and it had error'ed out.  Uninstalling and reinstalling did not help.  I completely removed python and all software associated with qobuz-dl with revo uninstaller to get a clean uninstall.  Rebooted, reinstalled, and the same error presents itself with any type of qobuz link to download.

**Comment by blissfuldot** [comment]
same here

**Comment by nkopas** [comment]
Probably has something to do with this...
https://torrentfreak.com/riaa-takes-down-popular-music-piracy-discord-over-adele-30-leak-211122/
I think RipRequests had a bot that pulled data from Qobuz.

**Comment by CobreDev** [comment]
+1 here, it was working perfectly a few days ago but now it's not

**Comment by martystack** [comment]
+1 Same issue

**Comment by ThinBucket82549** [comment]
They updated their api thats why.

**Comment by pinus2** [comment]
> They updated their api thats why.

Is this fixable?

**Comment by ThinBucket82549** [comment]
Maybe. In a couple of weeks or maybe days. It depends on what the devs do

**Comment by Jodel-D18** [comment]
Hopefully it should be possible to amend the code.  I am able to log in Qobuz using Strawberry Music Player and stream HiRes files.  Using the Qobuz tab in Strawberry lets me configure it with my password / secret app credentials, so with luck qobuz-dl application can be modified without too much hassle.  I don't understand the code well enough myself make any changes.

**Comment by pinus2** [comment]
> Hopefully it should be possible to amend the code. I am able to log in Qobuz using Strawberry Music Player and stream HiRes files. Using the Qobuz tab in Strawberry lets me configure it with my password / secret app credentials, so with luck qobuz-dl application can be modified without too much hassle. I don't understand the code well enough myself make any changes.

I can login to Qobuz too with streamrip, so is a minor problem to solve

**Comment by nkopas** [comment]
So, I did some sleuthing and the root cause is the "userLibrary/getAlbumsList" API endpoint used to validate and choose from one of the two possible secrets no longer exists.

**Comment by vitiko98** [comment]
Thanks for the report. I'm gonna take a look at the API changes.

**Comment by vitiko98** [comment]
Fixed! You can update the tool with `pip install qobuz-dl --upgrade`.

**Comment by Schmosworld** [comment]
The update didn't fix for me. I have reset credentials as well as uninstalled and reinstalled. Here's what I'm getting:

Traceback (most recent call last):
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\Scripts\qobuz-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\cli.py", line 176, in main
    _handle_commands(qobuz, arguments)
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\cli.py", line 83, in _handle_commands
    qobuz.download_list_of_urls(arguments.SOURCE)
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\core.py", line 180, in download_list_of_urls
    self.handle_url(url)
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\core.py", line 168, in handle_url
    self.download_from_id(item_id, type_dict["album"])
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\core.py", line 105, in download_from_id
    dloader.download_id_by_type(not album)
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\downloader.py", line 61, in download_id_by_type
    self.download_release()
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\downloader.py", line 81, in download_release
    format_info = self._get_format(meta)
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\downloader.py", line 286, in _get_format
    self.client.get_track_url(track_dict["id"], fmt_id=self.quality)
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\qopy.py", line 150, in get_track_url
    return self.api_call("track/getFileUrl", id=id, fmt_id=fmt_id)
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\qopy.py", line 114, in api_call
    raise InvalidAppSecretError("Invalid app secret.\n" + RESET)
qobuz_dl.exceptions.InvalidAppSecretError: Invalid app secret.
Reset your credentials with 'qobuz-dl -r'

**Comment by barbz127** [comment]
Still broken here too - I can browse with "fun" now which I couldnt with the previous version but Im unable to export

**Comment by vitiko98** [comment]
@Schmosworld @barbz127 Please send me the command you have used.

**Comment by Schmosworld** [comment]
qobuz-dl dl "album address"

This is with default folder and quality options

**Comment by barbz127** [comment]
> @Schmosworld @barbz127 Please send me the command you have used.

qobuz-dl dl http://artisturl

**Comment by vitiko98** [comment]
> > @Schmosworld @barbz127 Please send me the command you have used.
> 
> qobuz-dl dl http://artisturl

I can't reproduce your issue. It's working fine for me:

```
$ qobuz-dl dl "https://play.qobuz.com/artist/22195"
Logging...
Logged: OK
Membership: Studio
Set max quality: 6 - 16 bit, 44.1kHz

Downloading all the music from Stevie Wonder (artist)!
48 downloads in queue

Downloading: Innervisions
Quality: FLAC (16/44.1)

76.2k/76.2k /// cover.jpg
10.5M/26.8M /// Too High
...
```
Like I've stated above, don't forget adding the `--upgrade` flag (`pip install qobuz-dl --upgrade`) if you haven't already.

**Comment by Schmosworld** [comment]
> > > @Schmosworld @barbz127 Please send me the command you have used.
> > 
> > 
> > qobuz-dl dl http://artisturl
> 
> I can't reproduce your issue. It's working fine for me:
> 
> ```
> $ qobuz-dl dl "https://play.qobuz.com/artist/22195"
> Logging...
> Logged: OK
> Membership: Studio
> Set max quality: 6 - 16 bit, 44.1kHz
> 
> Downloading all the music from Stevie Wonder (artist)!
> 48 downloads in queue
> 
> Downloading: Innervisions
> Quality: FLAC (16/44.1)
> 
> 76.2k/76.2k /// cover.jpg
> 10.5M/26.8M /// Too High
> ...
> ```
> 
> Like I've stated above, don't forget adding the `--upgrade` flag (`pip install qobuz-dl --upgrade`) if you haven't already.

Try it using an album URL. This is the one I was trying 

https://play.qobuz.com/album/0603497882755

**Comment by barbz127** [comment]
> pip install qobuz-dl --upgrade

Thankyou - I have updated and it did the download to latest version

Same error with url you are testing with

`  c:\temp> qobuz-dl dl https://play.qobuz.com/album/0603497882755
Logging...
Logged: OK
Membership: Studio
Set max quality: 27 - 24 bit, >96kHz

Traceback (most recent call last):
  File "c:\users\paul\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\paul\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\paul\AppData\Local\Programs\Python\Python37\Scripts\qobuz-dl.exe\__main__.py", line 7, in <module>
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\qobuz_dl\cli.py", line 176, in main
    _handle_commands(qobuz, arguments)
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\qobuz_dl\cli.py", line 83, in _handle_commands
    qobuz.download_list_of_urls(arguments.SOURCE)
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\qobuz_dl\core.py", line 180, in download_list_of_urls
    self.handle_url(url)
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\qobuz_dl\core.py", line 168, in handle_url
    self.download_from_id(item_id, type_dict["album"])
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\qobuz_dl\core.py", line 105, in download_from_id
    dloader.download_id_by_type(not album)
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\qobuz_dl\downloader.py", line 61, in download_id_by_type
    self.download_release()
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\qobuz_dl\downloader.py", line 81, in download_release
    format_info = self._get_format(meta)
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\qobuz_dl\downloader.py", line 287, in _get_format
    if not track_url_dict
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\qobuz_dl\qopy.py", line 150, in get_track_url
    return self.api_call("track/getFileUrl", id=id, fmt_id=fmt_id)
  File "c:\users\paul\appdata\local\programs\python\python37\lib\site-packages\qobuz_dl\qopy.py", line 114, in api_call
    raise InvalidAppSecretError("Invalid app secret.\n" + RESET)
qobuz_dl.exceptions.InvalidAppSecretError: Invalid app secret.
Reset your credentials with 'qobuz-dl -r'`

**Comment by vitiko98** [comment]
I've added a little more of verbosity to the `InvalidAppSecretError` message in order to catch the error. Please update the tool again and send me the output.

**Comment by barbz127** [comment]
> I've added a little more of verbosity to the `InvalidAppSecretError` message in order to catch the error. Please update the tool again and send me the output.

`qobuz_dl.exceptions.InvalidAppSecretError: Invalid app secret: {'status': 'error', 'code': 400, 'message': 'Invalid Request Signature parameter (7dcdc52a4c9fa1b53690449ff6fd8177)'}.`

**Comment by Schmosworld** [comment]
C:\Users\DJ>qobuz-dl dl https://play.qobuz.com/album/0603497882755
Logging...
Logged: OK
Membership: Studio
Set max quality: 6 - 16 bit, 44.1kHz

Traceback (most recent call last):
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\Scripts\qobuz-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\cli.py", line 176, in main
    _handle_commands(qobuz, arguments)
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\cli.py", line 83, in _handle_commands
    qobuz.download_list_of_urls(arguments.SOURCE)
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\core.py", line 180, in download_list_of_urls
    self.handle_url(url)
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\core.py", line 168, in handle_url
    self.download_from_id(item_id, type_dict["album"])
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\core.py", line 105, in download_from_id
    dloader.download_id_by_type(not album)
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\downloader.py", line 61, in download_id_by_type
    self.download_release()
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\downloader.py", line 81, in download_release
    format_info = self._get_format(meta)
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\downloader.py", line 286, in _get_format
    self.client.get_track_url(track_dict["id"], fmt_id=self.quality)
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\qopy.py", line 150, in get_track_url
    return self.api_call("track/getFileUrl", id=id, fmt_id=fmt_id)
  File "C:\Users\DJ\AppData\Local\Programs\Python\Python39\lib\site-packages\qobuz_dl\qopy.py", line 114, in api_call
    raise InvalidAppSecretError("Invalid app secret.\n" + RESET)
qobuz_dl.exceptions.InvalidAppSecretError: Invalid app secret.
Reset your credentials with 'qobuz-dl -r'

**Comment by oneinchashhh** [comment]
same for me

**Comment by vitiko98** [comment]
I was able to download the album without problems. Is the error showing on every release? I still can't reproduce. :/

**Comment by windward-earth** [comment]
I am getting the same error as others:

qobuz_dl.exceptions.InvalidAppSecretError: Invalid app secret: {'status': 'error', 'code': 400, 'message': 'Invalid Request Signature parameter (3a9e7658fd44ea5g2s2a5a147c1661d)'}.

**Comment by Schmosworld** [comment]
> I was able to download the album without any problems. Is the error showing on every release? I still can't reproduce. :/

Every release here. Could you show the syntax yo are using? Mine looks like this:

qobuz-dl dl https://play.qobuz.com/album/0603497882755

No quotes or symbols

**Comment by PhamIsoBar** [comment]
Hi @vitiko98 ,
I'm using on window and command line to download from txt file. I have tried removed and re-install I got issue
![image](https://user-images.githubusercontent.com/38066524/143524099-8de5ea7c-68d2-4ad2-838c-245036cae97a.png)

Please help to review..
Thank you for your efforts

**Comment by MrBonesHOK** [comment]
@vitiko98 still not working for me, here's everything (even after resetting my config file):

C:\Users\xxxx>qobuz-dl dl https://play.qobuz.com/album/pbl5r3kt3kdaa -q 27
Logging...
Logged: OK
Membership: Studio
Set max quality: 27 - 24 bit, >96kHz

Traceback (most recent call last):
  File "E:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Program Files\Python39\Scripts\qobuz-dl.exe\__main__.py", line 7, in <module>
  File "E:\Program Files\Python39\lib\site-packages\qobuz_dl\cli.py", line 176, in main
    _handle_commands(qobuz, arguments)
  File "E:\Program Files\Python39\lib\site-packages\qobuz_dl\cli.py", line 83, in _handle_commands
    qobuz.download_list_of_urls(arguments.SOURCE)
  File "E:\Program Files\Python39\lib\site-packages\qobuz_dl\core.py", line 180, in download_list_of_urls
    self.handle_url(url)
  File "E:\Program Files\Python39\lib\site-packages\qobuz_dl\core.py", line 168, in handle_url
    self.download_from_id(item_id, type_dict["album"])
  File "E:\Program Files\Python39\lib\site-packages\qobuz_dl\core.py", line 105, in download_from_id
    dloader.download_id_by_type(not album)
  File "E:\Program Files\Python39\lib\site-packages\qobuz_dl\downloader.py", line 61, in download_id_by_type
    self.download_release()
  File "E:\Program Files\Python39\lib\site-packages\qobuz_dl\downloader.py", line 81, in download_release
    format_info = self._get_format(meta)
  File "E:\Program Files\Python39\lib\site-packages\qobuz_dl\downloader.py", line 286, in _get_format
    self.client.get_track_url(track_dict["id"], fmt_id=self.quality)
  File "E:\Program Files\Python39\lib\site-packages\qobuz_dl\qopy.py", line 153, in get_track_url
    return self.api_call("track/getFileUrl", id=id, fmt_id=fmt_id)
  File "E:\Program Files\Python39\lib\site-packages\qobuz_dl\qopy.py", line 115, in api_call
    raise InvalidAppSecretError(
qobuz_dl.exceptions.InvalidAppSecretError: Invalid app secret: {'status': 'error', 'code': 400, 'message': 'Invalid Request Signature parameter (b586f598d13c8d358476126c2df3113e)'}.
Reset your credentials with 'qobuz-dl -r'

**Comment by pinus2** [comment]
> I was able to download the album without any problems. Is the error showing on every release? I still can't reproduce. :/

Not working also for me, i received this message when i try ti download something, fun mode works and i can see the list of the albums, bit when i download something i cant:

Logged: OK
Membership: Studio
Set max quality: 27 - 24 bit, >96kHz

Searching albums for "frank zappa".
qobuz-dl will attempt to download the first 1 results.
Traceback (most recent call last):
  File "/bin/qobuz-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/qobuz_dl/cli.py", line 176, in main
    _handle_commands(qobuz, arguments)
  File "/usr/lib/python3.8/site-packages/qobuz_dl/cli.py", line 88, in _handle_commands
    qobuz.lucky_mode(query)
  File "/usr/lib/python3.8/site-packages/qobuz_dl/core.py", line 212, in lucky_mode
    self.download_list_of_urls(results)
  File "/usr/lib/python3.8/site-packages/qobuz_dl/core.py", line 180, in download_list_of_urls
    self.handle_url(url)
  File "/usr/lib/python3.8/site-packages/qobuz_dl/core.py", line 168, in handle_url
    self.download_from_id(item_id, type_dict["album"])
  File "/usr/lib/python3.8/site-packages/qobuz_dl/core.py", line 105, in download_from_id
    dloader.download_id_by_type(not album)
  File "/usr/lib/python3.8/site-packages/qobuz_dl/downloader.py", line 61, in download_id_by_type
    self.download_release()
  File "/usr/lib/python3.8/site-packages/qobuz_dl/downloader.py", line 81, in download_release
    format_info = self._get_format(meta)
  File "/usr/lib/python3.8/site-packages/qobuz_dl/downloader.py", line 286, in _get_format    self.client.get_track_url(track_dict["id"], fmt_id=self.quality)
  File "/usr/lib/python3.8/site-packages/qobuz_dl/qopy.py", line 153, in get_track_url
    return self.api_call("track/getFileUrl", id=id, fmt_id=fmt_id)
  File "/usr/lib/python3.8/site-packages/qobuz_dl/qopy.py", line 115, in api_call
    raise InvalidAppSecretError(
qobuz_dl.exceptions.InvalidAppSecretError: Invalid app secret: {'status': 'error', 'code': 400, 'message': 'Invalid Request Signature parameter (51c77ef81b713e1351fbc7186895d427)'}.
Reset your credentials with 'qobuz-dl -r'

**Comment by coreyoilar** [comment]
Not working for me either.  I updated python to the latest and still no success.  I normally run this function with a batch file but it just stops and freezes after the following is displayed:

C:\Users\xxxxx>qobuz-dl dl -e "c:\Users\xxxxx\Desktop\Commands\qb1.txt"
Logging...
Logged: OK
Membership: Studio
Set max quality: 27 - 24 bit, >96kHz

qobuz-dl will download 53 urls from file: c:\Users\xxxxx\Desktop\Commands\qb1.txt

after this is displayed... it just sits there.  I let it run for about 3 hours and still hangs when reading the commands from the batch text file.

**Comment by 2517416** [comment]
![20211126190613](https://user-images.githubusercontent.com/87647415/143571613-6b51e385-51b0-48a8-b856-26771f4289ad.png)
the same question，tks for ur hard working，bro!!!

**Comment by nkopas** [comment]
I'm able to get it working by just hardcoding the secret at the bottom of qopy.py...

```
    def cfg_setup(self):
#        for secret in self.secrets:
#            if secret:
#                if self.test_secret(secret):
#                    self.sec = secret
#                    break
        self.sec = "979549437fcc4a3faad4867b5cd25dcb"
        if not hasattr(self, "sec"):
            raise InvalidAppSecretError("Invalid app secret.\n" + RESET)
```

**Comment by pinus2** [comment]
> I'm able to get it working by just hardcoding the secret at the bottom of qopy.py...
> 
> ```
>     def cfg_setup(self):
> #        for secret in self.secrets:
> #            if secret:
> #                if self.test_secret(secret):
> #                    self.sec = secret
> #                    break
>         self.sec = "979549437fcc4a3faad4867b5cd25dcb"
>         if not hasattr(self, "sec"):
>             raise InvalidAppSecretError("Invalid app secret.\n" + RESET)
> ```

Where you can find the secret? In the config file?

**Comment by nkopas** [comment]
> Where you can find the secret? In the config file?

Yes, but I think it's the same list of two secrets for everyone. You should just be able to use the same value I listed in my snippet.

**Comment by pinus2** [comment]
> > Where you can find the secret? In the config file?
> 
> Yes, but I think it's the same list of two secrets for everyone. You should just be able to use the same value I listed in my snippet.

Thank to your help i have found the problem. In the config file you have to remove one of the two secrets phrase. this is the config file after secret phrase removed. Work well :) 
![image](https://user-images.githubusercontent.com/50369938/143592979-3c1d4ad5-d4c6-43be-b882-9ab1e18b2fcb.png)

**Comment by pinus2** [comment]
> I was able to download the album without any problems. Is the error showing on every release? I still can't reproduce. :/

Read my comment above, maybe can hel you fix the problem. In the config file there was two secrets phrase. When i have remove one the two all works well again. Thank you very much for your work

**Comment by whatsnew1202** [comment]
Both methods seem to work for me: hardcoding the secret at the bottom of qopy.py OR remove one of the two secrets in config file. Thanks for your help!

**Comment by Jodel-D18** [comment]
Just tried making the change to the config file.  Removed one of the two secrets and it is now working again.
Thank you very much for your efforts in resolving this issue!

**Comment by MrBonesHOK** [comment]
Can confirm, opened the .ini config file, removed 1 of the 2 'secrets' & saved & now works like a champ (should look like below w/your 'secret' in place of the xxxx)):
secrets = ,xxxx
folder_format = {artist} - {album} ({year}) [{bit_depth}B-{sampling_rate}kHz]
track_format = {tracknumber}. {tracktitle}
smart_discography = false

**Comment by pinus2** [comment]
> Can confirm, opened the .ini config file, removed 1 of the 2 'secrets' & saved & now works like a champ (should look like below w/your 'secret' in place of the xxxx)): secrets = ,xxxx folder_format = {artist} - {album} ({year}) [{bit_depth}B-{sampling_rate}kHz] track_format = {tracknumber}. {tracktitle} smart_discography = false

@MrBonesHOK i think that secrets is ,979549437fcc4a3faad4867b5cd25dcb for all

**Comment by Aminizm** [comment]
> I'm able to get it working by just hardcoding the secret at the bottom of qopy.py...
> 
> ```
>     def cfg_setup(self):
> #        for secret in self.secrets:
> #            if secret:
> #                if self.test_secret(secret):
> #                    self.sec = secret
> #                    break
>         self.sec = "979549437fcc4a3faad4867b5cd25dcb"
>         if not hasattr(self, "sec"):
>             raise InvalidAppSecretError("Invalid app secret.\n" + RESET)
> ```

works for me, thanks!

**Comment by Notorious2Beat** [comment]
> I'm able to get it working by just hardcoding the secret at the bottom of qopy.py...
> 
> ```
>     def cfg_setup(self):
> #        for secret in self.secrets:
> #            if secret:
> #                if self.test_secret(secret):
> #                    self.sec = secret
> #                    break
>         self.sec = "979549437fcc4a3faad4867b5cd25dcb"
>         if not hasattr(self, "sec"):
>             raise InvalidAppSecretError("Invalid app secret.\n" + RESET)
> ```

How can I do this if I'm on android?

**Comment by vitiko98** [comment]
I just found the problem. The `test_secret` method was always returning `True`, even with wrong or empty `secret` strings-. The method was updated. It should work now. Thanks!
